/***
 *
 * -----------------------------------------------------------
 * customerCollection information from & to
 *
 * -----------------------------------------------------------
 */


package com.my.store.Ecommerce.Model;

import jakarta.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.File;
import java.io.Serializable;

/***
 *
 * @Author phedwin
 *
 * customer firstHand details
 * User: ID-->Autogenerated at the back, UserName, Password, Email, Role
 *
 * the customer role will further be used to know when customer is either
 *
 * a normal user who has registered or a new user who needs to register.
 *
 * in any case it's a new user. There is no product access, user can only view
 * or register and access the products and shipping
 */


/**
 *
 *
 * map this class inside the Database
 *
 * this is based on MongoDb, so at @Document annotation instead of Entity
 *
 * same thing its just the relationship and manipulation
 */

@Document

/***
 *
 * implement Seriazalable to use the gen data in the various forms
 *
 * reading at the back and front plus req & response
 */
public class customerInfo implements Serializable {


    /***
     *
     * the id on the document is always autogenerated but having it here
     * is a good starting point.
     */

    @Id
    private long ID;
    private File photo;
    private String username;
    private String password;
    private String firstName;
    private String lastName;
//    public String email;

    /***
     *
     * create instance and expand the constructor
     *
     * for the purposes of returning a json like structure during testing
     */
    public customerInfo(long ID, File photo, String username, String password,
                        String firstName, String lastName) {
        this.ID = ID;
        this.firstName = firstName;
        this.lastName = lastName;
        this.photo = photo;
        this.username = username;

    }

    /**
     * generate random password to the user or allow custom
     */


    public customerInfo() {
        this.password = generateRandomPassword();
    }

    public customerInfo(String password) {
        this.password = password;
    }

    private String generateRandomPassword() {
        // Code to generate a random password
        return "generated_password";
    }

    public void setPassword(String password) {
        this.password = password;
    }

    private String getPassword() {
        return password;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public File getPhoto() {
        return photo;
    }

    public void setPhoto(File photo) {
        this.photo = photo;
    }




    @Override
    public String toString() {
        return "CustomerInfo{" +
                "id" + ID + '\'' +
                ", username" + username + '\'' +
                ", firstname' " + firstName +
                ", lastname'" + lastName +

        "}";
    }
}


/**
 *
 * @phedwin
 * @Date ----------------------Jan, 28 2023------------------------------
 */